[package]
name = "aocrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
dirs = "5.0.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde_json = "1.0"
text_io = "0.1.13"
log = "0.4.22"
